# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1f06358d67f0b7440a84313946dfa3ab9effa040d45865dd65440097f0927e1050f5d0eddcf6ef1d6bb16af422f492cd3b3ab7393ea075b36049724e17c93da

test:
  secret_key_base: 5af9f4c224270e08f30c9ab65389a76bb2d8e6558de54eb70a0d996bf0cc32b72917b5b725aa5241aa609f2774d3905e903ba0b2317f5a862fecd4031313f771

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
